# Generated by Django 5.0.8 on 2024-10-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="default.png", upload_to="images/%Y/%m/%d/"
            ),
        ),
    ]
